### ISSUE TITLE
How can I edit .carousel__slide css?

### ISSUE THREAD

**Issue by tohedul** [marcreichel/angular-carousel#4]
Hi, I want to edit/customise 'carousel__slide' css class. How can I do that? Suppose I want to set padding left and right 0 of  carousel__slide. Also if I don't want to show bullet points, how can I do that? There aren't any property for that.

**Comment by marcreichel** [comment]
Hi,

you can edit the `.carousel__slide` css by simply styling it in your css. Just make sure you use `!important`. So for example:

```css
.carousel__slide {
    padding-left: 0 !important;
    padding-right: 0 !important;
}
```

would work. But you got a point here. I will definitely improve on this as `!important` is not a friendly solution. 😅 

For hiding the bullets there is an option though. By setting `[bullets]` to `false` the bullets disappear.

```html
<angular-carousel [bullets]="false">
    <!-- ... --->
</angular-carousel>
```
